# Generated by Django 2.0 on 2019-08-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='score',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
